title: Christian Oliveros
email: christianol_work@outlook.com
description: Computer Scientist | Game & Media Technology Enthusiast
baseurl: "" 
url: "https://maniatic0.github.io"

# Social Links
twitter: "https://twitter.com/CHChistris"
linkedin: "https://ve.linkedin.com/in/christian-oliveros-69a98311a"
github: "https://github.com/maniatic0"
itchio: "https://maniatico.itch.io/"
